### ISSUE TITLE
Why put disassembled contents in current buffer?

### ISSUE THREAD

**Issue by xiongtx** [gbalats/autodisass-java-bytecode#3]
First of all, thanks for creating something like this! It's inspired me to work on my own version.

I'm wondering why it's necessary to go through the trouble of:

``` emacs-lisp
(kill-buffer orig-buffer-name)
(switch-to-buffer (generate-new-buffer orig-buffer-name))
...
(set-visited-file-name nil)
(setq buffer-file-name orig-buffer-file-name)
```

Why not just created a new buffer and set its `default-directory` to the directory of the original file?

**Comment by gbalats** [comment]
How would just setting the `default-directory` simplify things? Wouldn't you still need to perform the other steps?

**Comment by xiongtx** [comment]
No need to set visited file name to `nil`, for one.

**Comment by gbalats** [comment]
Setting visited file name to `nil` is probably redundant right now; a leftover from a previous version where the already existing buffer was getting reused and no new buffer was created.

However, it indicates that setting `buffer-file-name` directly is the intended behavior, instead of `(set-visited-file-name orig-buffer-file-name)`, since we do not want to update the file contents if the buffer ever gets saved.
